import { getRoadsideSummary } from '@/app/actions/roadside';
import { notFound } from 'next/navigation';

type Props = { searchParams: Promise<{ t?: string }> };

export default async function RoadsideViewPage({ searchParams }: Props) {
  const params = await searchParams;
  const token = params.t?.trim();
  if (!token) notFound();

  const summary = await getRoadsideSummary(token);
  if (!summary || summary.error) notFound();

  return (
    <div className="min-h-screen bg-midnight-ink text-soft-cloud p-4 pb-8">
      <header className="border-b border-white/10 pb-4 mb-6">
        <h1 className="text-xl font-bold text-cyber-amber">ROADSIDE READY</h1>
        <p className="text-soft-cloud/70 text-sm mt-1">Read-only document summary</p>
        {summary.org_name && (
          <p className="text-soft-cloud/80 font-medium mt-2">{summary.org_name}</p>
        )}
      </header>

      <div className="space-y-6 max-w-lg mx-auto">
        {/* ELD Status */}
        <section className="rounded-xl bg-card border border-white/10 p-4">
          <h2 className="font-semibold text-cyber-amber mb-2">ELD Status</h2>
          <p className="text-soft-cloud/90 text-sm">
            {summary.eld_status?.message ?? summary.eld_status?.status ?? 'Compliant — ELD and hours available in cab.'}
          </p>
        </section>

        {/* Insurance / Permits */}
        <section className="rounded-xl bg-card border border-white/10 p-4">
          <h2 className="font-semibold text-cyber-amber mb-2">Insurance / Permits</h2>
          {summary.insurance_permits && summary.insurance_permits.length > 0 ? (
            <ul className="space-y-1 text-sm text-soft-cloud/90">
              {summary.insurance_permits.map((item: { type: string; expiry: string | null }, i: number) => (
                <li key={i}>
                  {item.type}
                  {item.expiry ? ` — expires ${item.expiry}` : ''}
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-soft-cloud/70 text-sm">No documents on file for this view.</p>
          )}
        </section>

        {/* Recent Maintenance */}
        <section className="rounded-xl bg-card border border-white/10 p-4">
          <h2 className="font-semibold text-cyber-amber mb-2">Recent Maintenance</h2>
          {summary.recent_maintenance && summary.recent_maintenance.length > 0 ? (
            <ul className="space-y-2 text-sm text-soft-cloud/90">
              {summary.recent_maintenance.map((item: { date: string; description: string | null }, i: number) => (
                <li key={i}>
                  <span className="text-soft-cloud/70">{item.date}</span>
                  {item.description ? ` — ${item.description}` : ''}
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-soft-cloud/70 text-sm">No recent maintenance records for this view.</p>
          )}
        </section>
      </div>

      <p className="text-soft-cloud/50 text-xs text-center mt-8">
        This link is temporary and read-only. Generated by VantagFleet.
      </p>
    </div>
  );
}
