import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { createAdminClient } from '@/lib/supabase/admin';
import { getDashboardOrgId } from '@/lib/admin';
import { cookies } from 'next/headers';
import archiver from 'archiver';
import sgMail from '@sendgrid/mail';

const BUCKET = 'dq-documents';
const FROM_EMAIL = process.env.SENDGRID_FROM_EMAIL ?? 'VantagFleet <info@vantagfleet.com>';

function complianceReportHtml(params: {
  carrierName: string;
  usdot: string;
  docTypes: string[];
  reportDate: string;
}): string {
  const { carrierName, usdot, docTypes } = params;
  const reportDate = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  const listItems = docTypes.length
    ? docTypes.map((t) => `        <li>${escapeHtml(t)}</li>`).join('\n')
    : '        <li>No documents on file</li>';
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>VantagFleet Compliance Report</title>
</head>
<body style="margin:0; padding:0; font-family: system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif; background-color: #f8fafc; color: #0f172a;">
  <div style="max-width: 640px; margin: 0 auto; padding: 32px 24px;">
    <div style="background: #0f172a; border-radius: 16px; overflow: hidden; box-shadow: 0 25px 50px -12px rgba(0,0,0,0.25);">
      <div style="background: linear-gradient(135deg, rgba(245,158,11,0.2) 0%, transparent 50%); padding: 28px 32px; border-bottom: 1px solid rgba(245,158,11,0.3);">
        <p style="margin: 0 0 4px; font-size: 11px; font-weight: 600; letter-spacing: 0.15em; text-transform: uppercase; color: #f59e0b;">VantagFleet</p>
        <h1 style="margin: 0; font-size: 24px; font-weight: 700; color: #fff;">Compliance Report</h1>
        <p style="margin: 8px 0 0; font-size: 13px; color: #94a3b8;">Official document package for roadside verification</p>
      </div>
      <div style="padding: 28px 32px;">
        <table style="width: 100%; border-collapse: collapse;">
          <tr>
            <td style="padding: 10px 0; font-size: 12px; color: #64748b; width: 140px;">Carrier</td>
            <td style="padding: 10px 0; font-size: 15px; font-weight: 600; color: #e2e8f0;">${escapeHtml(carrierName)}</td>
          </tr>
          <tr>
            <td style="padding: 10px 0; font-size: 12px; color: #64748b;">USDOT</td>
            <td style="padding: 10px 0; font-size: 15px; font-weight: 600; color: #f59e0b;">${escapeHtml(usdot)}</td>
          </tr>
          <tr>
            <td style="padding: 10px 0; font-size: 12px; color: #64748b;">Report date</td>
            <td style="padding: 10px 0; font-size: 14px; color: #cbd5e1;">${reportDate}</td>
          </tr>
        </table>
        <div style="margin-top: 24px; padding-top: 24px; border-top: 1px solid rgba(255,255,255,0.1);">
          <p style="margin: 0 0 8px; font-size: 12px; font-weight: 600; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.05em;">Documents included (ZIP attachment)</p>
          <ul style="margin: 0; padding-left: 20px; font-size: 14px; color: #cbd5e1; line-height: 1.8;">
${listItems}
          </ul>
        </div>
        <p style="margin: 24px 0 0; font-size: 13px; color: #64748b;">This report was generated by the carrier via VantagFleet Roadside Shield. Attached ZIP contains the referenced compliance documents for verification.</p>
      </div>
      <div style="padding: 16px 32px; background: rgba(0,0,0,0.2); border-top: 1px solid rgba(255,255,255,0.06);">
        <p style="margin: 0; font-size: 11px; color: #64748b;">VantagFleet — Fleet compliance and document management</p>
      </div>
    </div>
  </div>
</body>
</html>`.trim();
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

export async function POST(request: NextRequest) {
  const supabase = await createClient();
  const cookieStore = await cookies();
  const orgId = await getDashboardOrgId(supabase, cookieStore);

  if (!orgId) {
    return jsonOrRedirect(request, { error: 'Not authorized' }, 401);
  }

  let officerEmail = '';
  const isJson = request.headers.get('content-type')?.includes('application/json');
  if (isJson) {
    try {
      const body = await request.json();
      officerEmail = (body?.officerEmail ?? '').trim();
    } catch {
      officerEmail = '';
    }
  } else {
    try {
      const formData = await request.formData();
      officerEmail = (formData.get('officerEmail') as string)?.trim() ?? '';
    } catch {
      officerEmail = '';
    }
  }

  if (!officerEmail || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(officerEmail)) {
    return jsonOrRedirect(request, { error: 'Invalid email' }, 400);
  }

  const admin = createAdminClient();
  const [{ data: org }, { data: docs }] = await Promise.all([
    supabase.from('organizations').select('name, usdot_number').eq('id', orgId).single(),
    supabase.from('compliance_docs').select('id, doc_type, file_path').eq('org_id', orgId),
  ]);

  const carrierName = (org as { name?: string } | null)?.name ?? 'Carrier';
  const usdot = (org as { usdot_number?: string | null } | null)?.usdot_number ?? '—';
  const docTypes = Array.from(new Set((docs ?? []).map((d: { doc_type: string }) => d.doc_type)));

  if (!docs?.length) {
    return jsonOrRedirect(request, { error: 'No documents to send' }, 400);
  }

  const archive = archiver('zip', { store: true });
  const chunks: Buffer[] = [];
  archive.on('data', (chunk: Buffer) => chunks.push(chunk));
  const archiveDone = new Promise<void>((resolve, reject) => {
    archive.on('end', () => resolve());
    archive.on('error', reject);
  });

  for (let i = 0; i < docs.length; i++) {
    const doc = docs[i];
    const { data: blob, error } = await admin.storage.from(BUCKET).download(doc.file_path);
    if (error || !blob) continue;
    const ext = doc.file_path.split('.').pop() || 'bin';
    const safeName = `${doc.doc_type.replace(/[^a-zA-Z0-9-_]/g, '_')}_${i + 1}.${ext}`;
    archive.append(Buffer.from(await blob.arrayBuffer()), { name: safeName });
  }

  archive.finalize();
  await archiveDone;
  const zipBuffer = Buffer.concat(chunks);
  const zipBase64 = zipBuffer.toString('base64');

  const key = process.env.SENDGRID_API_KEY?.trim();
  if (!key) {
    return jsonOrRedirect(request, { error: 'Email not configured' }, 500);
  }

  const reportDate = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  const html = complianceReportHtml({
    carrierName,
    usdot,
    docTypes,
    reportDate,
  });

  sgMail.setApiKey(key);
  try {
    await sgMail.send({
      to: officerEmail,
      from: FROM_EMAIL,
      subject: `VantagFleet Compliance Report — ${carrierName} (USDOT ${usdot})`,
      text: `VantagFleet Compliance Report for ${carrierName}, USDOT ${usdot}. Report date: ${reportDate}. Documents included: ${docTypes.join(', ')}. See attached ZIP.`,
      html,
      attachments: [
        {
          content: zipBase64,
          filename: `vantagfleet-compliance-report-${usdot || 'carrier'}.zip`,
          type: 'application/zip',
          disposition: 'attachment',
        },
      ],
    });
  } catch (err) {
    console.error('[roadside-shield share] SendGrid error:', err);
    return jsonOrRedirect(request, { error: 'Failed to send email' }, 500);
  }

  return jsonOrRedirect(request, { ok: true }, 200);
}

function jsonOrRedirect(
  request: NextRequest,
  body: { ok?: boolean; error?: string },
  status: number
): NextResponse {
  const isJson = request.headers.get('content-type')?.includes('application/json');
  if (isJson) {
    return NextResponse.json(body, { status });
  }
  const url = new URL('/driver/roadside-shield', request.url);
  if (body.ok) url.searchParams.set('sent', '1');
  else url.searchParams.set('error', body.error ? encodeURIComponent(body.error) : '1');
  return NextResponse.redirect(url);
}
