-- Carrier integrations (Samsara, Motive, FMCSA): store API key or Client ID per org.
-- Compliance alerts: generated by sync when driver has expired CDL/med or vehicle missing inspection.

CREATE TABLE IF NOT EXISTS public.carrier_integrations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  provider TEXT NOT NULL CHECK (provider IN ('samsara', 'motive', 'fmcsa')),
  credential TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(org_id, provider)
);

CREATE INDEX IF NOT EXISTS idx_carrier_integrations_org_id ON public.carrier_integrations(org_id);
CREATE INDEX IF NOT EXISTS idx_carrier_integrations_provider ON public.carrier_integrations(provider);

ALTER TABLE public.carrier_integrations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can manage integrations in own orgs" ON public.carrier_integrations;
CREATE POLICY "Users can manage integrations in own orgs"
  ON public.carrier_integrations FOR ALL
  USING (org_id IN (SELECT public.user_org_ids()))
  WITH CHECK (org_id IN (SELECT public.user_org_ids()));

COMMENT ON TABLE public.carrier_integrations IS 'Per-carrier API keys / client IDs for Samsara, Motive, FMCSA.';

-- Compliance alerts: expired CDL/med, missing inspection, etc.
CREATE TABLE IF NOT EXISTS public.compliance_alerts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  alert_type TEXT NOT NULL CHECK (alert_type IN ('expired_cdl', 'missing_inspection')),
  entity_type TEXT NOT NULL CHECK (entity_type IN ('driver', 'vehicle')),
  entity_id UUID NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  resolved_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_compliance_alerts_org_id ON public.compliance_alerts(org_id);
CREATE INDEX IF NOT EXISTS idx_compliance_alerts_created_at ON public.compliance_alerts(created_at DESC);

ALTER TABLE public.compliance_alerts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view compliance_alerts in own orgs" ON public.compliance_alerts;
CREATE POLICY "Users can view compliance_alerts in own orgs"
  ON public.compliance_alerts FOR SELECT
  USING (org_id IN (SELECT public.user_org_ids()));

-- Inserts/updates via service role (sync job) bypass RLS.

COMMENT ON TABLE public.compliance_alerts IS 'Alerts from compliance sync: expired CDL/med card, missing vehicle inspection.';
